controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

    jeu-de-cartes_directory:
    path: /card
    controller: App\Controller\ControllerCardController::list
